CREATE TABLE PRODUCTS(
ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(32) NOT NULL,
CATEGORY VARCHAR(32) NOT NULL,
COLOR VARCHAR(20) NOT NULL,
PARAMETER VARCHAR(32) NOT NULL,
COUNT NUMBER,
PRICE NUMBER,
);
