INSERT INTO USERS(FIRST_NAME, LAST_NAME, AGE)
VALUES('John', 'Doe', 45);
INSERT INTO USERS(FIRST_NAME, LAST_NAME, AGE)
VALUES('July', 'Jun', 23);
INSERT INTO USERS(FIRST_NAME, LAST_NAME, AGE)
VALUES('Denis', 'Danny', 24);
INSERT INTO USERS(FIRST_NAME, LAST_NAME, AGE)
VALUES('Ann', 'Cho', 30);
INSERT INTO USERS(FIRST_NAME, LAST_NAME, AGE)
VALUES('Kate', 'Bong', 55);