INSERT INTO PRODUCTS(NAME, CATEGORY, COLOR, PARAMETER, COUNT, PRICE)
VALUES('Apple', 'Fruits', 'Green', 'Fresh', 79, 10);
INSERT INTO PRODUCTS(NAME, CATEGORY, COLOR, PARAMETER, COUNT, PRICE)
VALUES('Banana', 'Fruits', 'Yellow', 'Fresh', 100, 30);

